spring:
  profiles:
    active: dev
server:
  #https端口号.
  port: 443
#  ssl:
#    #证书的路径.
#    key-store: classpath:keystore.p12
#    #证书密码，请修改为您自己证书的密码.
#    key-store-password: xinwei2020
#    #秘钥库类型
#    key-store-type: PKCS12
#    #证书别名
#    key-alias: tomcat
pagehelper:
  #  dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql
logging:
  config: classpath:logback-spring.xml