server:
  port: 8081
  thymeleaf:
    prefix: classpath:/templates/
#  http:
#    httpPort: 9090
spring:
  mvc:
    static-path-pattern: /**
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/authentic?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: wjwl2020!!
    # 使用druid数据源
    # type: mysql
  redis:
    host: 127.0.0.1
    port: 6379
    password: wjwl2020!!
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 30000
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml







